"""สร้างเอกสาร README.md อัตโนมัติหลังรันเสร็จ อธิบายว่าแต่ละไฟล์ใน
Config.SAVE_PATH (ตัวเลข/log — ผลลัพธ์การประเมิน, checkpoint, config
snapshot) และ Config.OUTPUT_PATH (ภาพ — กราฟ/heatmap/gallery ทั้งหมด)
เก็บอะไรไว้บ้าง โครงสร้างข้างในเป็นยังไง และเอาไปทำอะไรต่อได้บ้าง

เป็น dynamic — เช็คว่าไฟล์ไหนมีอยู่จริงในโฟลเดอร์ ณ ตอนเรียกก่อนเขียน
คำอธิบาย ไม่ list ไฟล์ที่ยังไม่เคยถูกสร้าง (เช่น cost_aware_sweep.csv
ที่จะมีก็ต่อเมื่อเคยรัน scripts/run_cost_aware.py มาก่อน หรือ
features_{split}.npz ที่มีก็ต่อเมื่อเคยรัน scripts/export_features.py)

เรียกจาก:
- scripts/train.py (ท้ายฟังก์ชัน main()) → เขียน SAVE_PATH/README.md
- scripts/visualize.py (ท้ายฟังก์ชัน main()) → เขียน OUTPUT_PATH/README.md

Automatically generates a README.md after a run, documenting what every
file in Config.SAVE_PATH (numeric/log — evaluation results, checkpoints,
config snapshot) and Config.OUTPUT_PATH (images — all plots/heatmaps/
galleries) holds, its internal structure, and what it can be used for.

Dynamic — checks which files actually exist in the folder at call time
before documenting them; never lists a file that was never produced
(e.g. cost_aware_sweep.csv only exists if scripts/run_cost_aware.py was
run beforehand, features_{split}.npz only if scripts/export_features.py
was run).

Called from:
- scripts/train.py (end of main()) → writes SAVE_PATH/README.md
- scripts/visualize.py (end of main()) → writes OUTPUT_PATH/README.md
"""
import glob
import os
from datetime import datetime
from typing import List


def _file_size_str(path: str) -> str:
    """ขนาดไฟล์แบบอ่านง่าย (KB/MB/GB) / human-readable file size."""
    if not os.path.exists(path):
        return 'N/A'
    size = float(os.path.getsize(path))
    for unit in ('B', 'KB', 'MB', 'GB'):
        if size < 1024.0:
            return f'{size:.1f} {unit}'
        size /= 1024.0
    return f'{size:.1f} TB'


def _exists_any(cfg_path: str, pattern: str) -> List[str]:
    """เช็คว่ามีไฟล์ตรง glob pattern อยู่จริงไหม (สำหรับไฟล์ที่ชื่อแปรผัน
    ตาม split เช่น scores_{split}.npz) คืน list ของไฟล์ที่เจอจริง

    Check whether any file matching the glob pattern actually exists
    (for filenames that vary by split, e.g. scores_{split}.npz). Returns
    the list of files actually found.
    """
    return sorted(glob.glob(os.path.join(cfg_path, pattern)))


# ═══════════════════════════════════════════════════════════════════════
# SAVE_PATH — ไฟล์ตัวเลข/log ทั้งหมด (checkpoint, metric, config snapshot)
# SAVE_PATH — all numeric/log files (checkpoints, metrics, config snapshot)
# ═══════════════════════════════════════════════════════════════════════

def write_save_path_readme(cfg) -> str:
    p = cfg.SAVE_PATH
    os.makedirs(p, exist_ok=True)
    sections = []

    sections.append(f"""# Artifacts ใน `{p}` (SAVE_PATH)

สร้างอัตโนมัติโดย `src/output_docs.py` เมื่อ {datetime.now().isoformat(timespec='seconds')}

โฟลเดอร์นี้เก็บ **ตัวเลข/log/checkpoint ทั้งหมด** — ไม่มีไฟล์ภาพเลย
(ภาพทั้งหมดอยู่ที่ `{cfg.OUTPUT_PATH}` แทน — ดู README.md ในนั้น)

Auto-generated by `src/output_docs.py` at {datetime.now().isoformat(timespec='seconds')}

This folder holds **all numeric/log/checkpoint files** — no images at
all (all images live in `{cfg.OUTPUT_PATH}` instead — see the README.md
there).

---
""")

    # ── history.json ──────────────────────────────────────────────────
    fp = os.path.join(p, 'history.json')
    if os.path.exists(fp):
        sections.append(f"""## `history.json` ({_file_size_str(fp)})

**เก็บอะไร**: training history รายเอพอค 5 key เท่ากันทุกตัว
(ยืนยันจาก `src/engine.py:train_autoencoder`):

| Key | ความหมาย | ใช้ label ไหม |
|---|---|---|
| `train_loss` | loss เฉลี่ยต่อ epoch บน `normal_loader` (train, normal เท่านั้น) | ไม่ใช้ |
| `val_loss` | loss เฉลี่ยบน validation **ทั้งชุด** (ผสม normal+anomaly) | ไม่ใช้เลย — label-free |
| `val_loss_normal` | loss เฉลี่ยบน validation **เฉพาะแถว normal** | ใช้เบา (รู้แค่ว่าแถวไหน known-normal) |
| `val_auroc` | AUROC บน validation ผ่าน scoring pipeline เดียวกับที่รายงานจริง | ใช้เต็ม (ต้องมี anomaly label) |
| `lr` | learning rate ณ epoch นั้น (จาก scheduler) | — |

แต่ละ key เป็น `list[float]` ความยาว = จำนวน epoch ที่เทรนจริง (**อาจน้อย
กว่า `Config.AE_EPOCHS`** ถ้า `EarlyStopping` สั่งหยุดก่อน — เช็คความยาว
list เพื่อรู้ว่าหยุดกี่ epoch)

**เอาไปทำอะไรได้**:
- Plot training curve เองแบบ custom (ไม่ต้องพึ่ง `plot_training_history()` ใน `visual.py`)
- หา best epoch เองด้วย monitor ต่างจากที่ตั้งไว้ตอนเทรน เช่น `int(np.argmin(history['val_loss_normal']))` เทียบกับ `int(np.argmax(history['val_auroc']))` — ดูว่า 2 monitor เห็นต่างกันไหม (สัญญาณว่า checkpoint selection sensitive ต่อ monitor แค่ไหน)
- เทียบ convergence speed ข้าม experiment (E0 vs E1 ที่ `LOSS`/`OPTIM` ต่างกัน) โดย plot หลาย `history.json` ซ้อนกัน
- เช็ค overfitting: ถ้า `train_loss` ลดต่อเนื่องแต่ `val_loss`/`val_auroc` เริ่มแย่ลง คือสัญญาณ overfit

**How to load**:
```python
import json
history = json.load(open('{fp}'))
print(f"เทรนจริง {{len(history['train_loss'])}} epoch")
```

**What it holds**: per-epoch training history, 5 keys always present
(confirmed from `src/engine.py:train_autoencoder`) — see table above.
Each key is a `list[float]` whose length equals the number of epochs
actually trained (**may be less than `Config.AE_EPOCHS`** if
`EarlyStopping` triggered early — check the list length to find out how
many epochs it actually ran).

**What you can do with it**: plot a custom training curve without
`plot_training_history()`; recompute the best epoch under a different
monitor than the one used at train time; compare convergence speed
across experiments by overlaying multiple `history.json` files; spot
overfitting when `train_loss` keeps dropping while `val_loss`/`val_auroc`
worsens.

---
""")

    # ── extractor_norm_stats.pt ───────────────────────────────────────
    fp = os.path.join(p, 'extractor_norm_stats.pt')
    if os.path.exists(fp):
        sections.append(f"""## `extractor_norm_stats.pt` ({_file_size_str(fp)})

**เก็บอะไร**: สถิติ normalize ของ feature ที่ fit จาก **train (normal
เท่านั้น) ครั้งเดียว** — **ไม่ใช่ feature ดิบของภาพไหนเลย** (ไฟล์เล็กมาก
เพราะเก็บแค่สถิติสรุป ไม่ใช่ array ต่อภาพ):

| Key | ความหมาย | Shape |
|---|---|---|
| `feat_mean` | ค่าเฉลี่ยต่อ channel | `(out_channels, 1, 1)` |
| `feat_std` | ส่วนเบี่ยงเบนมาตรฐานต่อ channel | `(out_channels, 1, 1)` |
| `out_channels` | จำนวน channel ของ feature (576 สำหรับ backbone=`tiny`/`small`, 768 สำหรับ `base`, 1152 สำหรับ `large` — ยืนยันด้วยการรัน architecture จริง) | scalar int |
| `spatial_size` | ขนาด (H, W) ของ feature map ก่อนเข้า AE (28×28 ทุก variant) | tuple |

**เอาไปทำอะไรได้**:
- Normalize feature ใหม่ตอน inference โดยไม่ต้อง fit ซ้ำ (ห้าม fit จาก val/test — จะเป็น data leakage ทันที): `normalized = (raw - feat_mean) / feat_std`
- แปลงกลับเป็น raw feature ได้ถ้าจำเป็น: `raw = normalized * feat_std + feat_mean`
- เช็คว่า backbone variant ไหนถูกใช้จริง (`out_channels`) โดยไม่ต้องเปิด `config.py`

**How to load**:
```python
import torch
stats = torch.load('{fp}', map_location='cpu')
print(stats['out_channels'], stats['spatial_size'])
```

**What it holds**: normalization statistics fitted once from train
(normal-only) — **not any image's raw feature** (tiny file, since it's
just summary statistics, not a per-image array). See table above for
keys.

**What you can do with it**: normalize new features at inference
without re-fitting (never re-fit from val/test — instant data leakage);
recover raw features via `raw = normalized * feat_std + feat_mean`;
check which backbone variant was actually used from `out_channels`
without opening `config.py`.

---
""")

    # ── threshold.json ─────────────────────────────────────────────────
    fp = os.path.join(p, 'threshold.json')
    if os.path.exists(fp):
        sections.append(f"""## `threshold.json` ({_file_size_str(fp)})

**เก็บอะไร** (ยืนยันจาก `src/io_utils.py:save_threshold`):

| Key | ความหมาย |
|---|---|
| `threshold` | threshold ที่ใช้ deploy จริง — percentile ของ score ภาพ normal ใน val |
| `percentile` | percentile ที่ใช้ (ค่า default 95.0 จาก `Config.THRESHOLD_PERCENTILE`) |
| `oracle_threshold` | max-F1 threshold บน val — **diagnostic เท่านั้น ไม่ได้ใช้รายงานผลจริง** เพราะใช้ label ของ anomaly ใน val ตรงๆ |
| `oracle_f1` | ค่า F1 ที่ oracle_threshold ให้ |

**เอาไปทำอะไรได้**:
- Apply threshold เดียวกันนี้กับภาพใหม่ตอน deploy จริง (อ่านค่าเดียว ไม่ต้องคำนวณ percentile ใหม่)
- เทียบช่องว่างระหว่าง `threshold` (deploy จริง) กับ `oracle_threshold` (best-possible บน val) — ถ้าห่างกันมาก แปลว่า percentile threshold ยังไม่ optimal เท่าที่ควรจะเป็นได้ (นี่คือแรงจูงใจของ `src/cost_aware.py` — ดู README section "Cost-Aware Threshold Selection")

**How to load**:
```python
import json
thr = json.load(open('{fp}'))
```

**What it holds**: `threshold` (real deployment threshold), `percentile`,
`oracle_threshold` (max-F1 on val, diagnostic only — never used for
reported metrics since it uses val anomaly labels directly),
`oracle_f1`.

**What you can do with it**: apply the same threshold to new images at
deployment (read one number, no need to recompute the percentile);
compare the gap between `threshold` and `oracle_threshold` — a large gap
signals the percentile threshold isn't close to optimal (this is exactly
the motivation behind `src/cost_aware.py`).

---
""")

    # ── scores_{split}.npz ──────────────────────────────────────────────
    for split in ('val', 'test'):
        fp = os.path.join(p, f'scores_{split}.npz')
        if os.path.exists(fp):
            sections.append(f"""## `scores_{split}.npz` ({_file_size_str(fp)})

**เก็บอะไร** (ยืนยันจาก `src/io_utils.py:save_scores`) — 7 array ต่อภาพใน split `{split}`:

| Key | เก็บอะไร | Type/Shape |
|---|---|---|
| `scores` | anomaly score ต่อภาพ (ก่อน threshold) | `float32`, `(N,)` |
| `y_true` | label จริง 0=normal, 1=anomaly | `int`, `(N,)` |
| `paths` | path เต็มของไฟล์ภาพต้นฉบับ | string, `(N,)` |
| `labels` | ชื่อ class แบบ string (`"good"`/`"defect"`) — **คนละตัวกับ `y_true`** | string, `(N,)` |
| `heatmaps` | error map หลัง upsample+smooth | `float32`, `(N, H, W)` |
| `orig_imgs` | ภาพต้นฉบับก่อน preprocess | `float32`, `(N, H, W, C)` |
| `preproc_imgs` | ภาพหลัง preprocess (เท่ากับ `orig_imgs` ถ้าโหมด RGB) | `float32`, `(N, H, W, C)` |

⚠️ **`labels` ≠ `y_true`** — ใช้ `y_true` เสมอสำหรับคำนวณ metric ใดๆ

**เอาไปทำอะไรได้**:
- คำนวณ metric ใดๆ ซ้ำโดยไม่ต้องรันโมเดลใหม่: `compute_metrics(scores, y_true, threshold)`
- Plot ROC/PR curve เอง
- ป้อนเข้า `src/cost_aware.py` สำหรับ cost-aware threshold sweep
- Re-render heatmap gallery โดยไม่ต้องรัน inference ใหม่
- วิเคราะห์ error แบบ per-image (join กับ `predictions_{split}.csv` ผ่าน `paths`)

**How to load** (แนะนำใช้ `io_utils.load_scores()` เสมอ ไม่ `np.load()` ดิบ กัน key ผิด):
```python
from src import io_utils
data = io_utils.load_scores('{split}', cfg)
scores, y_true = data['scores'], data['y_true']
```

**What it holds**: 7 arrays per image in the `{split}` split (see table
above). ⚠️ `labels` ≠ `y_true` — always use `y_true` for any metric
computation.

**What you can do with it**: recompute any metric without re-running the
model; plot ROC/PR curves yourself; feed into `src/cost_aware.py`'s
threshold sweep; re-render heatmap galleries without new inference;
per-image error analysis by joining with `predictions_{split}.csv` on
`paths`.

---
""")

    # ── best_autoencoder.pth / autoencoder_final.pth ────────────────────
    fp_best = os.path.join(p, 'best_autoencoder.pth')
    if os.path.exists(fp_best):
        sections.append(f"""## `best_autoencoder.pth` ({_file_size_str(fp_best)})

**เก็บอะไร**: **`model.state_dict()` ดิบๆ เท่านั้น** (ยืนยันจาก
`src/engine.py:EarlyStopping.__call__` — `torch.save(model.state_dict(), self.save_path)`)
**ไม่มี metadata ห่อไว้เลย** ต่างจาก `autoencoder_final.pth` ด้านล่าง —
เซฟทับทุกครั้งที่ monitor metric (`Config.AE_MONITOR`) ดีขึ้นระหว่างเทรน
คือ checkpoint ที่ **"ดีที่สุด" ตาม monitor ที่เลือก** ไม่ใช่ epoch สุดท้าย
เสมอไป

**เอาไปทำอะไรได้**: โหลดกลับมาใช้ inference/deploy จริง (นี่คือ
checkpoint ที่ควรใช้ ไม่ใช่ `autoencoder_final.pth`)

**How to load**:
```python
from src.model.autoencoder import FeatureAutoencoder
ae = FeatureAutoencoder(feat_ch=..., bottleneck_ch=...)
ae.load_state_dict(torch.load('{fp_best}', map_location='cpu'))
```

**What it holds**: **raw `model.state_dict()` only**, no metadata
wrapper (unlike `autoencoder_final.pth` below) — overwritten every time
the monitored metric (`Config.AE_MONITOR`) improves during training.
This is the checkpoint that's "best" per the chosen monitor, not
necessarily the last epoch.

**What you can do with it**: load it back for real inference/deployment
— this is the checkpoint that should actually be used, not
`autoencoder_final.pth`.

---
""")

    fp_final = os.path.join(p, 'autoencoder_final.pth')
    if os.path.exists(fp_final):
        sections.append(f"""## `autoencoder_final.pth` ({_file_size_str(fp_final)})

**เก็บอะไร** (ยืนยันจาก `scripts/train.py`): dict ที่มี metadata ห่อไว้
— **คนละไฟล์กับ `best_autoencoder.pth`**:

| Key | ความหมาย |
|---|---|
| `model_state` | `state_dict()` ของ AE ที่ epoch **สุดท้าย** (ไม่ใช่ epoch ที่ดีที่สุด) |
| `backbone` | ชื่อ backbone variant ที่ใช้ |
| `feat_ch` | จำนวน channel ของ feature |
| `bottleneck` | ขนาด bottleneck |
| `threshold` | deployment threshold ณ ตอนเซฟ |
| `timestamp` | เวลาที่เซฟ |

⚠️ **อาจไม่ใช่ checkpoint เดียวกับ `best_autoencoder.pth`** — ถ้า
`EarlyStopping` ไม่ได้ trigger ที่ epoch สุดท้ายพอดี สองไฟล์นี้จะเป็นคนละ
weight กัน

**เอาไปทำอะไรได้**: debug/เทียบว่า epoch สุดท้ายกับ epoch ที่ดีที่สุดต่างกันแค่ไหน, resume training ต่อจากจุดสุดท้าย (ต้องใช้ตัวนี้ ไม่ใช่ `best_autoencoder.pth`)

**How to load**:
```python
ckpt = torch.load('{fp_final}', map_location='cpu')
ae.load_state_dict(ckpt['model_state'])
```

**What it holds**: a dict with metadata (see table above) — **a
different file from `best_autoencoder.pth`**. `model_state` is the
**last** epoch's weights, not the best one.

⚠️ **May not be the same checkpoint as `best_autoencoder.pth`** — if
`EarlyStopping` didn't trigger exactly at the final epoch, these two
files hold different weights.

**What you can do with it**: debug/compare how different the last epoch
is from the best epoch; resume training from the exact last state (must
use this file, not `best_autoencoder.pth`).

---
""")

    # ── final_results.json ───────────────────────────────────────────────
    fp = os.path.join(p, 'final_results.json')
    if os.path.exists(fp):
        sections.append(f"""## `final_results.json` ({_file_size_str(fp)})

**เก็บอะไร**: สรุปผล run นี้แบบเต็ม — ไฟล์หลักสำหรับเทียบ experiment
ข้าม run (self-documenting, ไม่ต้องย้อนไปดู `config.py` ตอนนั้นตั้งค่าอะไรไว้):

| Key | ความหมาย |
|---|---|
| `experiment`, `backbone`, `method` | metadata พื้นฐานของ run |
| `feat_ch`, `bottleneck` | สถาปัตยกรรม |
| `threshold`, `ae_epochs`, `best_epoch`, `monitor` | สรุปผลการเทรน |
| `best_val_loss`, `best_val_auroc` | ค่าที่ epoch ดีที่สุด |
| `config` | **snapshot เต็มของทุก field ใน `Config`** (ผ่าน `dataclasses.asdict()`) |
| `naive_baselines` | ผล 3 baseline อ้างอิง (`always_normal`/`always_anomaly`/`random_prior`) แยก val/test พร้อม `seed` ที่ใช้ |
| `results` | metric เต็มชุดของโมเดลจริง แยก val/test (`auc`, `ap`, `acc`, `precision`, `recall`, `f1`, `tt`/`tf`/`ft`/`ff`, `auto_clear_rate`, `escape_rate`, `residual_fcr`) |
| `timestamp` | เวลาที่รันเสร็จ |

**เอาไปทำอะไรได้**:
- **เทียบ experiment หลาย run** — โหลดหลายไฟล์ `final_results.json` มา build ตาราง comparison (นี่คือหน้าที่ของ `compare_experiments.py`)
- **ดูว่า config อะไรถูกใช้จริง** โดยไม่ต้องเปิด `config.py` — มีประโยชน์มากตอนย้อนกลับไปดู experiment เก่าหลังแก้ `config.py` ไปแล้ว
- **เทียบโมเดลจริงกับ naive baseline** ในไฟล์เดียวกัน — เช่น `results['test']['escape_rate']` เทียบกับ `naive_baselines['test']['always_normal']['escape_rate']`

**How to load**:
```python
import json
r = json.load(open('{fp}'))
print(r['results']['test']['auc'], r['naive_baselines']['test']['always_anomaly']['escape_rate'])
```

**What it holds**: a full summary of this run — the primary file for
comparing experiments across runs (self-documenting, no need to
cross-reference what `config.py` held at the time). See table above for
keys.

**What you can do with it**: compare multiple experiments by loading
several `final_results.json` files (this is what `compare_experiments.py`
does); check exactly which config was used without opening `config.py`;
compare the real model against the naive baselines within the same file.

---
""")

    # ── predictions_{split}.csv ────────────────────────────────────────
    for split in ('val', 'test'):
        fp = os.path.join(p, f'predictions_{split}.csv')
        if os.path.exists(fp):
            sections.append(f"""## `predictions_{split}.csv` ({_file_size_str(fp)})

**เก็บอะไร**: prediction ระดับภาพ 1 แถวต่อ 1 ภาพ:

| Column | ความหมาย |
|---|---|
| `path` | path ของภาพ |
| `label` | ชื่อ class string (`"good"`/`"defect"`) |
| `y_true` | label จริง 0/1 |
| `score` | anomaly score |
| `y_pred` | prediction 0/1 (จาก threshold ที่ใช้จริง) |
| `correct` | ทายถูกไหม (0/1) |

**เอาไปทำอะไรได้**:
- หาภาพที่ **escape** (defect หลุด) เจาะจง: filter `y_true==1 & y_pred==0` — เอา `path` ไปดูภาพจริงว่าทำไมโมเดลพลาด
- หาภาพที่ **false alarm**: filter `y_true==0 & y_pred==1`
- Sort ตาม `score` เพื่อดู borderline case ใกล้ threshold ที่สุด (เสี่ยงเปลี่ยนผลถ้า threshold ขยับนิดเดียว)

**How to load**:
```python
import pandas as pd
df = pd.read_csv('{fp}')
escapes = df[(df['y_true']==1) & (df['y_pred']==0)]
```

**What it holds**: one row per image — see table above.

**What you can do with it**: find specific **escape** cases
(`y_true==1 & y_pred==0`) to inspect why the model missed them; find
**false alarms** (`y_true==0 & y_pred==1`); sort by `score` to see
borderline cases closest to the threshold.

---
""")

    # ── gallery_index.csv (ย้ายมาจาก OUTPUT_PATH) ──────────────────────
    fp = os.path.join(p, 'gallery_index.csv')
    if os.path.exists(fp):
        sections.append(f"""## `gallery_index.csv` ({_file_size_str(fp)})

*(สร้างโดย `scripts/visualize.py` — ย้ายมาไว้ที่นี่แล้วเพราะเป็นตัวเลข/tabular ไม่ใช่ภาพ)*

**เก็บอะไร**: ดัชนีของทุกภาพที่ปรากฏใน gallery ทั้งหมด (`val`+`test`
รวมกัน) — `split`, `idx_in_split`, `filename`, `path`, `label_gt`,
`pred_label`, `score`, `correct`

**เอาไปทำอะไรได้**: เป็น index กลางสำหรับ join กับภาพ gallery ใน
`{cfg.OUTPUT_PATH}` — หาว่าภาพไหนอยู่ตำแหน่งไหนใน gallery ไฟล์ไหน

*(Produced by `scripts/visualize.py` — moved here since it's
numeric/tabular, not an image.)*

**What it holds**: an index of every image appearing in any gallery
(`val`+`test` combined) — see columns above.

**What you can do with it**: a central index to cross-reference with the
gallery images in `{cfg.OUTPUT_PATH}` — find which image sits where in
which gallery file.

---
""")

    # ── roc_curve_data_{split}.csv (เขียนโดย visualize.py) ──────────────
    for split in ('val', 'test'):
        fp = os.path.join(p, f'roc_curve_data_{split}.csv')
        if os.path.exists(fp):
            sections.append(f"""## `roc_curve_data_{split}.csv` ({_file_size_str(fp)})

*(สร้างโดย `scripts/visualize.py` — ไม่ใช่ output ของ `train.py`)*

**เก็บอะไร**: จุดดิบทุกจุดบนเส้น ROC curve ของ split `{split}` — 1 แถวต่อ
1 จุดตัด (threshold candidate) ที่ `sklearn.roc_curve()` คำนวณให้:

| Column | ความหมาย |
|---|---|
| `fpr` | False Positive Rate ณ จุดนั้น |
| `tpr` | True Positive Rate (recall) ณ จุดนั้น |
| `threshold` | ค่า score threshold ที่ทำให้ได้ fpr/tpr คู่นั้น |

จำนวนแถว = จำนวน unique score value ใน split นั้น (ไม่ใช่ค่าคงที่)

**เอาไปทำอะไรได้**:
- เปิดดู/plot ใน Excel หรือ tool อื่นที่ไม่ใช่ Python โดยไม่ต้องรันโค้ดใดๆ เพิ่ม
- **Input ให้ multi-seed ROC aggregation** — ถ้าทำ multi-seed (10 seed ตามแผนที่วางไว้) ต้องใช้ไฟล์นี้ของแต่ละ seed มา interpolate เข้าแกน FPR เดียวกันก่อน average (vertical averaging) ไม่ต้อง re-run `visualize.py`/โหลด `scores_{split}.npz` ใหม่ทุกครั้ง
- หา threshold ที่จุด fpr/tpr เฉพาะเจาะจงได้ตรงๆ โดยไม่ต้อง sweep เอง

*(Produced by `scripts/visualize.py` — not part of `train.py`'s output.)*

**What it holds**: every raw point on the ROC curve for split `{split}`
— one row per threshold candidate that `sklearn.roc_curve()` computed.
See table above for columns. Row count = number of unique score values
in that split (not a fixed number).

**What you can do with it**: open/plot in Excel or any non-Python tool
without running any extra code; **feed into multi-seed ROC aggregation**
— if doing multi-seed (10 seeds per the plan discussed), this file per
seed is what gets interpolated onto a common FPR axis before averaging
(vertical averaging), without needing to re-run `visualize.py` or reload
`scores_{split}.npz` each time; look up the threshold at a specific
fpr/tpr point directly without sweeping yourself.

---
""")

    # ── cost_aware_sweep.csv (optional — เฉพาะถ้าเคยรัน run_cost_aware.py) ──
    fp = os.path.join(p, 'cost_aware_sweep.csv')
    if os.path.exists(fp):
        sections.append(f"""## `cost_aware_sweep.csv` ({_file_size_str(fp)})

*(ไฟล์นี้มีเพราะเคยรัน `scripts/run_cost_aware.py` มาก่อน — ไม่ใช่ output ปกติของ `train.py`)*

**เก็บอะไร**: ผล cost-aware threshold sweep 1 แถวต่อ 1 ค่า `r` —
`r`, `threshold`, `val_cost`, `val_fn`, `val_fp`, `test_escape_rate`,
`test_precision`, `test_recall`, `test_f1`, `test_auto_clear_rate`

**เอาไปทำอะไรได้**: plot cost-sensitivity curve (escape_rate vs r),
เลือก threshold ผ่าน `find_elbow_r()`/`select_recall_constrained_threshold()`
ใน `src/cost_aware.py`

*(This file exists because `scripts/run_cost_aware.py` was run before —
not part of `train.py`'s normal output.)*

**What it holds**: cost-aware threshold sweep results, one row per `r`
value.

**What you can do with it**: plot the cost-sensitivity curve, pick a
threshold via `find_elbow_r()`/`select_recall_constrained_threshold()`.

---
""")

    # ── features_{split}.npz (optional — เฉพาะถ้าเคยรัน export_features.py) ──
    for split in ('train', 'val', 'test'):
        fp = os.path.join(p, f'features_{split}.npz')
        if os.path.exists(fp):
            sections.append(f"""## `features_{split}.npz` ({_file_size_str(fp)})

*(ไฟล์นี้มีเพราะเคยรัน `scripts/export_features.py` มาก่อน — ไม่ใช่ output ปกติของ `train.py`)*

**เก็บอะไร**: feature เต็ม spatial map จาก frozen ConvNeXt (post-normalize,
**pre-AE** — ไม่ผ่าน autoencoder เลย) — ใหญ่กว่า `scores_{split}.npz`
มาก เพราะไม่ได้ reduce channel:

| Key | Type/Shape |
|---|---|
| `features` | `float32`/`float16`, `(N, C, H, W)` |
| `y_true`, `paths`, `labels` | เหมือนกับใน `scores_{split}.npz` |

**เอาไปทำอะไรได้**: fit unsupervised method อื่น (PatchCore-style memory
bank, PaDiM Gaussian, clustering, one-class SVM) — `features_train.npz`
ใช้ fit, `features_val.npz`/`features_test.npz` ใช้ประเมิน

*(This file exists because `scripts/export_features.py` was run before
— not part of `train.py`'s normal output.)*

**What it holds**: full spatial feature maps from the frozen ConvNeXt
(post-normalize, **pre-AE**) — much larger than `scores_{split}.npz`
since channels aren't reduced.

**What you can do with it**: fit other unsupervised methods
(PatchCore-style memory bank, PaDiM, clustering, one-class SVM) —
`features_train.npz` for fitting, `features_val.npz`/`features_test.npz`
for evaluation.

---
""")

    content = ''.join(sections)
    out_path = os.path.join(p, 'README.md')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return out_path


# ═══════════════════════════════════════════════════════════════════════
# OUTPUT_PATH — ไฟล์ภาพทั้งหมด (กราฟ/heatmap/gallery)
# OUTPUT_PATH — all image files (plots/heatmaps/galleries)
# ═══════════════════════════════════════════════════════════════════════

def write_output_path_readme(cfg) -> str:
    p = cfg.OUTPUT_PATH
    os.makedirs(p, exist_ok=True)
    sections = []

    sections.append(f"""# ภาพผลลัพธ์ใน `{p}` (OUTPUT_PATH)

สร้างอัตโนมัติโดย `src/output_docs.py` เมื่อ {datetime.now().isoformat(timespec='seconds')}

โฟลเดอร์นี้เก็บ **ไฟล์ภาพ (.png) ทั้งหมด** — ไม่มีไฟล์ตัวเลข/CSV/JSON เลย
(ย้ายไปอยู่ที่ `{cfg.SAVE_PATH}` แทนแล้ว — ดู README.md ในนั้นสำหรับ
`final_results.json`, `predictions_{{split}}.csv`, `gallery_index.csv`)

สร้างโดย `scripts/visualize.py` (อ่าน artifact จาก `{cfg.SAVE_PATH}`
เท่านั้น ไม่รัน inference ใหม่)

Auto-generated by `src/output_docs.py` at {datetime.now().isoformat(timespec='seconds')}

This folder holds **all image (.png) files** — no numeric/CSV/JSON files
at all (those now live in `{cfg.SAVE_PATH}` instead — see the README.md
there for `final_results.json`, `predictions_{{split}}.csv`,
`gallery_index.csv`).

Produced by `scripts/visualize.py` (reads artifacts from
`{cfg.SAVE_PATH}` only, never re-runs inference).

---
""")

    image_docs = [
        ('eda_class_distribution.png',
         'จำนวนภาพต่อ class (normal/anomaly) แยก val/test — เช็ค class imbalance ก่อนตีความ metric อื่น',
         'Image count per class (normal/anomaly), split by val/test — check class imbalance before interpreting other metrics.'),
        ('training_history.png',
         'กราฟ train_loss, val_loss/val_loss_normal, val_auroc, learning rate ต่อ epoch พร้อมจุด best epoch — ดูว่าเทรน converge ดีไหม/overfit ไหม',
         'train_loss, val_loss/val_loss_normal, val_auroc, and learning rate per epoch with the best-epoch marker — check convergence/overfitting.'),
        ('roc_curves.png',
         'ROC curve (FPR vs TPR) แยก val/test พร้อม AUC — คำนวณสดจาก scores/y_true ใน SAVE_PATH ตอนรัน visualize.py',
         'ROC curve (FPR vs TPR) for val/test with AUC — computed live from scores/y_true in SAVE_PATH when visualize.py runs.'),
        ('pr_curves.png',
         'Precision-Recall curve แยก val/test — สำคัญกว่า ROC ตอน class imbalanced สูง',
         'Precision-Recall curve for val/test — more informative than ROC under heavy class imbalance.'),
        ('confusion_matrices.png',
         'Confusion matrix (heatmap 2×2) แยก val/test ที่ threshold จริงที่ใช้ deploy',
         '2×2 confusion matrix heatmap for val/test at the actual deployment threshold.'),
        ('score_distributions.png',
         'Histogram ของ anomaly score แยกตาม normal/anomaly พร้อมเส้น threshold — ดู separation ของสอง class ด้วยตา',
         'Histogram of anomaly scores split by normal/anomaly with the threshold line — visually inspect class separation.'),
        ('heatmaps_*.png',
         'ภาพตัวอย่าง (สุ่ม 20 ภาพ) พร้อม error-map heatmap overlay แยก val/test — มี suffix `_preproc` เพิ่มถ้า `COLOR_MODE != RGB` (โชว์ภาพที่โมเดลเห็นจริง แทน RGB ต้นฉบับ)',
         'Sample images (20, sampled) with the error-map heatmap overlaid, split by val/test — an extra `_preproc` suffix appears if `COLOR_MODE != RGB` (shows the actual model-input image instead of original RGB).'),
        ('gallery_original_*.png / gallery_processed_*.png',
         '`original` = เฉพาะภาพ RGB จริง, `processed` = ภาพ RGB + heatmap overlay — จัดเป็น grid หลายภาพต่อ 1 ไฟล์',
         '`original` = real RGB images only, `processed` = RGB + heatmap overlay — arranged as a multi-image grid per file.'),
        ('gallery_preproc_*.png / gallery_preproc_overlay_*.png',
         'เหมือนคู่บนแต่เป็นภาพหลัง preprocessing จริง (grayscale/CLAHE) — มีความหมายเฉพาะเมื่อ `COLOR_MODE != RGB`',
         'Same as the pair above but using the actual preprocessed image (grayscale/CLAHE) — only meaningful when `COLOR_MODE != RGB`.'),
    ]

    for pattern, th_desc, en_desc in image_docs:
        if '*' in pattern:
            first_pattern = pattern.split(' / ')[0]
            matches = _exists_any(p, first_pattern)
            second = pattern.split(' / ')
            if len(second) > 1:
                matches += _exists_any(p, second[1])
        else:
            matches = [os.path.join(p, pattern)] if os.path.exists(os.path.join(p, pattern)) else []
        if not matches:
            continue
        found_list = '\n'.join(f'  - `{os.path.basename(m)}` ({_file_size_str(m)})' for m in sorted(set(matches)))
        sections.append(f"""## `{pattern}`

**พบไฟล์จริง**:
{found_list}

**คืออะไร**: {th_desc}

**What it is**: {en_desc}

---
""")

    # gallery จาก browse_gallery() — ชื่อไฟล์ dynamic มาก (แปรผันตาม split/label/pred_label/correct)
    # เก็บทุกไฟล์ gallery_*.png ที่เหลือ (ยังไม่ถูกจับคู่ pattern ข้างบน) มาแสดงแบบ list เดี่ยว
    already_matched = set()
    for pattern, _, _ in image_docs:
        for pat in pattern.split(' / '):
            already_matched.update(os.path.basename(m) for m in _exists_any(p, pat))
    remaining_galleries = [m for m in _exists_any(p, 'gallery_*.png')
                           if os.path.basename(m) not in already_matched]
    if remaining_galleries:
        found_list = '\n'.join(f'  - `{os.path.basename(m)}` ({_file_size_str(m)})' for m in remaining_galleries)
        sections.append(f"""## `gallery_{{split}}_{{label}}_{{pred_label}}[_correct|_incorrect].png`

**พบไฟล์จริง**:
{found_list}

**คืออะไร**: Gallery 3 คอลัมน์ (ภาพต้นฉบับ | error map | overlay) จาก
`browse_gallery()` กรองเฉพาะกลุ่มที่ระบุในชื่อไฟล์ — เช่น
`gallery_test_defect_normal.png` = ภาพที่ label จริงเป็น `defect` แต่โมเดล
ทายว่า `normal` (**คือ escape case ที่มองเห็นภาพจริงได้**) ชื่อไฟล์
ประกอบจาก `split`, `label` (ground truth), `pred_label` (สิ่งที่โมเดลทาย),
และ `correct`/`incorrect` ถ้าระบุไว้ตอนเรียก

**What it is**: 3-column gallery (original | error map | overlay) from
`browse_gallery()`, filtered to the group named in the filename — e.g.
`gallery_test_defect_normal.png` = images whose true label is `defect`
but the model predicted `normal` (**a visual look at actual escape
cases**). Filenames are built from `split`, `label` (ground truth),
`pred_label` (what the model predicted), and `correct`/`incorrect` if
specified at call time.

---
""")

    content = ''.join(sections)
    out_path = os.path.join(p, 'README.md')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return out_path